name = "alarm"
main = "src/src/index.js"
compatibility_date = "2023-08-23"
workers_dev = true

[[d1_databases]]
binding = "DATABASE"
database_id = "1af5ccc5-1936-4da4-be7c-90fdf0052471"
database_name = "alarm-db"
